##############################################
# BOOM Consumer ZTF — Deployment
##############################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boom-consumer-ztf
  namespace: umn-babamul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boom-consumer-ztf
  template:
    metadata:
      labels:
        app: boom-consumer-ztf
    spec:
      containers:
        - name: consumer-ztf
          image: ghcr.io/keshavmajithia/boom:latest
          command: ["/app/kafka_consumer", "ztf"]
          env:
            - name: BOOM_DATABASE__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: boom-secrets
                  key: BOOM_DATABASE__PASSWORD
            - name: BOOM_API__AUTH__SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: boom-secrets
                  key: BOOM_API__AUTH__SECRET_KEY
            - name: BOOM_API__AUTH__ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: boom-secrets
                  key: BOOM_API__AUTH__ADMIN_PASSWORD
            - name: BOOM_DATABASE__HOST
              value: "mongo"
            - name: BOOM_DATABASE__USERNAME
              value: "mongoadmin"
            - name: BOOM_REDIS__HOST
              value: "valkey"
            - name: BOOM_KAFKA__CONSUMER__ZTF__GROUP_ID
              value: "boom-ztf-nrp"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4317"
          volumeMounts:
            - name: boom-config
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
      volumes:
        - name: boom-config
          configMap:
            name: boom-config
