apiVersion: v1
kind: Secret
metadata:
  name: boom-secrets
  namespace: umn-babamul
type: Opaque
stringData:
  BOOM_DATABASE__PASSWORD: "YOUR_MONGO_PASSWORD"
  BOOM_API__AUTH__SECRET_KEY: "YOUR_API_SECRET_KEY"
  BOOM_API__AUTH__ADMIN_PASSWORD: "YOUR_ADMIN_PASSWORD"
  KAFKA_ADMIN_PASSWORD: "YOUR_KAFKA_ADMIN_PASSWORD"
  KAFKA_READONLY_PASSWORD: "YOUR_KAFKA_READONLY_PASSWORD"
